project_id = "hyuaucoffkknqlwkgdmp"

[functions.generate-questions]
verify_jwt = true

[functions.analyze-psychometric]
verify_jwt = false

[functions.notify-assessment-created]
verify_jwt = false

[functions.notify-candidate-completed]
verify_jwt = false